new deploy, take 2

diff --git a/main.yml b/main.yml
--- a/main.yml
+++ b/main.yml
@@ -42,7 +42,7 @@ Resources:
         - Key: Name 
           Value: !Ref AWS::StackName
   InstanceRole:
-    Type: "AWS::IAM::Role"
+    Type: AWS::IAM::Role
     Properties:
       AssumeRolePolicyDocument:
         Version: "2012-10-17"
@@ -54,29 +54,12 @@ Resources:
           Action: sts:AssumeRole
       ManagedPolicyArns:
         - arn:aws:iam::aws:policy/CloudWatchFullAccess
-        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
         - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
       Tags:
         - Key: Name
           Value: !Ref AWS::StackName
-  DeploymentRole: 
-    Type: AWS::IAM::Role
-    Properties:
-      AssumeRolePolicyDocument:
-        Version: "2012-10-17"
-        Statement: 
-          Effect: Allow
-          Principal:
-            Service:
-              - codepipeline.amazonaws.com
-              - codedeploy.amazonaws.com
-              - codebuild.amazonaws.com
-          Action: sts:AssumeRole
-      ManagedPolicyArns:
-        - arn:aws:iam::aws:policy/PowerUserAccess
-        - arn:aws:iam::aws:policy/CloudWatchFullAccess
   InstanceProfile:
-    Type: "AWS::IAM::InstanceProfile"
+    Type: AWS::IAM::InstanceProfile
     Properties:
       Roles:
         - Ref: InstanceRole
@@ -84,7 +67,7 @@ Resources:
     Type: AWS::EC2::Instance
     CreationPolicy:
       ResourceSignal:
-        Timeout: PT15M
+        Timeout: PT5M
         Count: 1
     Metadata:
       AWS::CloudFormation::Init:
@@ -92,11 +75,12 @@ Resources:
           packages:
             yum:
               ruby: []
+              wget: []
           files:
             /home/ec2-user/install:
               source: !Sub "https://aws-codedeploy-${AWS::Region}.s3.amazonaws.com/latest/install"
               mode: "000755"
-          commands: 
+          commands:
             00-install-cd-agent:
               command: "./install auto"
               cwd: "/home/ec2-user/"
@@ -109,36 +93,62 @@ Resources:
         - !GetAtt SecurityGroup.GroupId
       UserData:
         Fn::Base64: !Sub |
-            #!/bin/bash -xe
-            # send script output to /tmp so we can debug boot failures
-            exec > /tmp/userdata.log 2>&1
-            # Update all packages
-            yum -y update
-            # Get latest cfn scripts; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/bestpractices.html#cfninit
-            yum install -y aws-cfn-bootstrap
-            cat > /tmp/install_script.sh << EOF
-              # START
-              echo "Setting up NodeJS Environment"
-              curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
-              # Dot source the files to ensure that variables are available within the current shell
-              . /home/ec2-user/.nvm/nvm.sh
-              . /home/ec2-user/.bashrc
-              # Install NVM, NPM, Node.JS
-              nvm alias default v12.7.0
-              nvm install v12.7.0
-              nvm use v12.7.0
-              # Create log directory
-              mkdir -p /home/ec2-user/app/logs
-            EOF
-            chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
-            sleep 1; su - ec2-user -c "/tmp/install_script.sh"
-            # Have CloudFormation install any files and packages from the metadata
-            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
-            # Signal to CloudFormation that the instance is ready
-            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
-      Tags: 
+          #!/bin/bash -xe
+
+          # send script output to /tmp so we can debug boot failures
+          exec > /tmp/userdata.log 2>&1
+
+          # Update all packages
+          yum -y update
+
+          # Get latest cfn scripts; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/bestpractices.html#cfninit
+          yum install -y aws-cfn-bootstrap
+
+          cat > /tmp/install_script.sh << EOF
+            # START
+
+            echo "Setting up NodeJS Environment"
+            curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
+
+            # Dot source the files to ensure that variables are available within the current shell
+            . /home/ec2-user/.nvm/nvm.sh
+            . /home/ec2-user/.bashrc
+
+            # Install NVM, NPM, Node.JS
+            nvm alias default v12.7.0
+            nvm install v12.7.0
+            nvm use v12.7.0
+
+            # Create log directory
+            mkdir -p /home/ec2-user/app/logs
+          EOF
+
+          chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
+          sleep 1; su - ec2-user -c "/tmp/install_script.sh"
+
+          # Have CloudFormation install any files and packages from the metadata
+          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
+
+          # Signal to CloudFormation that the instance is ready
+          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
+      Tags:
         - Key: Name
           Value: !Ref AWS::StackName
+  DeploymentRole:
+    Type: AWS::IAM::Role
+    Properties:
+      AssumeRolePolicyDocument:
+        Version: "2012-10-17"
+        Statement:
+          Effect: Allow
+          Principal:
+            Service:
+              - "codepipeline.amazonaws.com"
+              - "codedeploy.amazonaws.com"
+              - "codebuild.amazonaws.com"
+          Action: sts:AssumeRole
+      ManagedPolicyArns:
+        - arn:aws:iam::aws:policy/PowerUserAccess
   BuildProject:
     Type: AWS::CodeBuild::Project
     Properties:
@@ -146,7 +156,7 @@ Resources:
       ServiceRole: !GetAtt DeploymentRole.Arn
       Artifacts:
         Type: CODEPIPELINE
-      Environment: 
+      Environment:
         Type: LINUX_CONTAINER
         ComputeType: BUILD_GENERAL1_SMALL
         Image: aws/codebuild/standard:2.0
@@ -203,7 +213,7 @@ Resources:
                 Owner: AWS
                 Version: 1
                 Provider: CodeBuild
-              InputArtifacts: 
+              InputArtifacts:
                 - Name: Source
               OutputArtifacts:
                 - Name: Build
